# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23cd30f2dda6dd22496fcff37e95ce01be29ce35172a9ac2ab3d16762c1ba6053a2cba51fe001eb16e7095393d83ce437a28cc42e1aedc58c1b205ab9d45f4ca

test:
  secret_key_base: fc29f1f852951dae2cc7f6ae5821df82665865f47097d377d66d3f0bd7060809d8bcd766fb102e6662cc0400c743ba3eb1beab9f79ce948a67c3e9b41b7b19d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
